# Generated by Django 3.2.13 on 2022-04-19 11:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_alter_customeuser_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customeuser',
            options={},
        ),
        migrations.AlterModelManagers(
            name='customeuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='customeuser',
            name='is_staff',
        ),
        migrations.AlterField(
            model_name='customeuser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='customeuser',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='customeuser',
            name='first_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='customeuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customeuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customeuser',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 19, 11, 4, 31, 433897)),
        ),
        migrations.AlterField(
            model_name='customeuser',
            name='last_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterModelTable(
            name='customeuser',
            table=None,
        ),
    ]
