# Generated by Django 3.2.13 on 2022-04-19 11:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_auto_20220419_1104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customeuser',
            options={'verbose_name': 'user'},
        ),
        migrations.AlterField(
            model_name='customeuser',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 19, 11, 5, 34, 334296)),
        ),
        migrations.AlterModelTable(
            name='customeuser',
            table='user',
        ),
    ]
