# Generated by Django 3.2.13 on 2022-04-19 11:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_auto_20220419_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeuser',
            name='first_name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='customeuser',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 19, 11, 6, 48, 265194)),
        ),
        migrations.AlterField(
            model_name='customeuser',
            name='last_name',
            field=models.CharField(default='', max_length=150),
        ),
    ]
