# Generated by Django 3.2.13 on 2022-04-21 05:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_auto_20220419_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResetPasswordModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(default='', max_length=127)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'reset_password',
            },
        ),
        migrations.AlterField(
            model_name='customeuser',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 21, 5, 24, 20, 399936)),
        ),
    ]
